---
- name: Create groups
  hosts: dev prod
  become: yes
  vars_files:
    - user_list.yml
  tasks:
    - name: add accounts
      group:
        name: "{{ item.group }}"
        state: present
      with_items: "{{ users }}"
- name: Create users
  hosts: dev prod
  become: yes
  vars_files:
    - user_list.yml
  tasks:
    - name: Add user
      user:
        name: "{{ item.name }}"
        password: "{{ 'redhat'| password_hash('sha512') }}" 
        groups: "{{ item.group }}"
        append: yes
      with_items: "{{ users }}"
